version: '3.8'

services:
  app:
    build: .
    image: commission-calculator:latest
    volumes:
      - ./:/app
    command: ["php", "script.php", "input.csv"]

  phpunit:
    build: .
    image: commission-calculator:latest
    volumes:
      - ./:/app
    command: ["./bin/phpunit"]
