version: '3.8'

services:
  app:
    build: .
    image: commission-calculator:latest
    ports:
      - "9000:9000"

  phpunit:
    build: .
    image: commission-calculator:latest
    command: ["/app/bin/phpunit"]

volumes:
  vendor:
